title: Midwest Bioinformatics Showcase
description: Connecting Researchers Across the Midwest
theme: minima
baseurl: ""
url: "https://midwest-bioinformatics-showcase.github.io"


future: true

collections:
  seminars:
    output: true
    permalink: /seminars/:name/

defaults:
  - scope:
      path: ""
      type: seminars
    values:
      layout: seminar

markdown: kramdown
plugins:
  - jekyll-feed

# --- navigation bar links ---
header_pages:
  - index.md
  - submit.md
  - seminars.md
  - organizers.md
  - participate.md